// 상품 할인율 상수
const BULK_PURCHASE_THRESHOLD = 30;
const BULE_PURCHASE_PRODUCT_THRESHOLD = 10;
const EXTRA_DISCOUT_PERCENT = 0.25;
const SUGGESTION_PRODUCT_INTERVAL = 60000;
const LUCKY_EVENT_SALE_INTERVAL = 30000;
const TUESDAY_DISCOUNT_AMOUNT_PERCENT = 0.1;

const PRODUCT_DISCOUT_MAP = {
  p1: 0.1,
  p2: 0.15,
  p3: 0.2,
  p4: 0.05,
  p5: 0.25,
};

export {
  BULK_PURCHASE_THRESHOLD,
  BULE_PURCHASE_PRODUCT_THRESHOLD,
  EXTRA_DISCOUT_PERCENT,
  SUGGESTION_PRODUCT_INTERVAL,
  LUCKY_EVENT_SALE_INTERVAL,
  TUESDAY_DISCOUNT_AMOUNT_PERCENT,
  PRODUCT_DISCOUT_MAP,
};
